Netappfiles update sdk with api version 2021 06 01
Azure-Samples/netappfiles-java-pool-change-sdk-sample pull request #4
Opened 2021-09-08 11:51 UTC by hildurhodd

Minimum changes made to support the new sdk version
- Use TokenCredential with AzureProfile instead of ServiceClientCredentials
- Use NetAppFilesManager instead of AzureNetAppFilesManagementClientImpl
- Remove Observables and CompletableFuture since it is not supported any more.
- Updated readme file to describe new way to authenticate

## Purpose

* Update to latest SDK  version: 1.0.0-beta.5

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[x] Other... Please describe: SDK Version update and changes to support that version
```

2021-09-20 16:22 UTC, paulomarquesc commented on src/main/java/poolchange/sdk/sample/main.java
> +            catch (Exception e)
>Exception [](http://example.com/codeflow?start=19&length=9)

CloudException got replaced by AzureError (at least in Python), and should not be replaced by the broader Exception, can you please apply the equivalent for Java? Please do the same on all samples.

2021-09-20 16:22 UTC, paulomarquesc requested changes
:clock1:

2021-09-21 18:03 UTC, AdelGhabboun approved these changes
Looks good

2021-09-23 15:49 UTC, paulomarquesc approved these changes
:shipit:

2021-09-24 08:27 UTC, merged